spring.application.name=campusequipmentloan

# Setup H2 Database connection
spring.datasource.url=jdbc:h2:mem:testdb

# Setup datasource driver
spring.datasource.driver-class-name=org.h2.Driver

# Setup database login credentials
spring.datasource.username=sa
spring.datasource.password=

# Automatically create tables based on entities from 'com.springboot.rest.entity'
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Prevent stack trace error from appearing
server.error.include-stacktrace=never
